name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      
      - run: npx lerna bootstrap
      - run: npx lerna run lint
      - run: npx lerna run build
      - run: npx lerna run test

